[package]
edition = "2021"
license.workspace = true
name = "fuzzy-sourcemap"
publish = false
version = "0.0.0"

[dependencies]
swc_core = {version = "*", features = ["common_sourcemap"]}

[dev-dependencies]
glob = "0.3.1"
insta = {version = "1.34.0"}
once_cell = "1.19.0"
