[workspace]
members = [
  "crates/*",
  "packages/swc-plugin-esm-serve", # "pyprojects/sphinx-jsx",
]
resolver = "2"

[workspace.package]
license = "MIT OR Apache-2.0"

[profile.release]
lto = true

[profile.swc-plugin]
inherits = "release"
lto = true
opt-level = "z"
strip = "symbols"
