[project]
authors = [{ name = "Tony Wu", email = "tonywu6@protonmail.com" }]
dependencies = [
  "aiofiles~=23.1.0",
  "asyncstdlib>=3.10.8",
  "click>=8.1.5",
  "importlib-resources>=6.0.0",
  "loguru>=0.7.0",
  "more-itertools>=9.1.0",
  "pexpect>=4.8.0",
  # "pydantic-settings>=2.0.2",
  "pydantic>=1.10.12,<2.0.0",
  "python-dotenv~=1.0.0",
  "ruamel-yaml>=0.17.32",
  "sphinx>=6.2.1",
  "tabulate>=0.9.0",
  "termcolor>=2.3.0",
  "tqdm>=4.65.0",
  "twisted>=22.10.0",
  "typing-extensions>=4.7.1",
  "urllib3<2.0.0",              # urllib3>=2.0.0 breaks requests-unixsocket
  "requests>=2.31.0",
  "requests-unixsocket>=0.3.0",
  "watchfiles>=0.20.0",
  "pathspec>=0.11.1",
]
description = "Documentation toolchain for SecretFlow"
name = "secretflow-doctools"
readme = "README.md"
requires-python = ">=3.8.15, <3.11"
dynamic = ["version"]

[project.scripts]
secretflow-doctools = 'secretflow_doctools.__main__:cli'

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.rye]
dev-dependencies = [
  "black>=23.7.0",
  "docutils-stubs>=0.0.22",
  "hatch>=1.7.0",
  "ipython>=8.12.2",
  "myst-parser~=2.0.0",
  "pytest>=7.4.0",
  "ruff>=0.0.284",
  "sphinx-autobuild>=2021.3.14",
  "sphinx-autodoc2~=0.4.2",
  "sphinx-intl>=2.1.0",
]
managed = true

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.version]
path = "pyproject/package.json"
# regex to match "version" in package.json
pattern = '"version": "(?P<version>[^"]+)"'

[tool.hatch.build]
only-include = ["pyproject/src", "pyproject/package.json"]
artifacts = ["**/node_modules/mdserver/dist"]
directory = "pyproject/dist"

[tool.hatch.build.targets.wheel]
sources = ["pyproject/src"]

[tool.hatch.build.targets.custom]
path = 'pyproject/scripts/hatch_build.py'
sources = ["pyproject/src"]

[tool.pytest.ini_options]
pythonpath = ["pyproject/src"]

[tool.black]
line-length = 88
target-versions = ["py38", "py39", "py310"]
extend-exclude = """
_pb2\\.pyi?
| _pb2_grpc\\.pyi?
"""

[tool.ruff]
line-length = 88
select = ["E", "F", "W", "B", "I"]
src = ["pyproject/src", "pyproject/tests"]

[tool.pyright]
include = ["pyproject/src"]
exclude = ["**/node_modules", "**/__pycache__"]
reportGeneralTypeIssues = "information"
reportOptionalMemberAccess = "information"
