[project]
authors = [{name = "Tony Wu", email = "tonywu6@protonmail.com"}]
classifiers = [
  "Private :: Do Not Upload",
]
dependencies = []
name = "monorepo"
readme = "README.md"
requires-python = ">=3.8.15, <3.11"
version = "0.0.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.rye.workspace]
members = ["pyprojects/*"]

[tool.rye]
dev-dependencies = [
  "black>=23.7.0",
  "docutils-stubs>=0.0.22",
  "hatch>=1.7.0",
  "ipython>=8.12.2",
  "myst-parser~=2.0.0",
  "pytest>=7.4.0",
  "ruff>=0.0.284",
  "sphinx-autobuild>=2021.3.14",
  "sphinx-autodoc2~=0.4.2",
  "sphinx-intl>=2.1.0",
  "maturin>=1.3.0",
  "jupyterlab>=4.0.7",
  "pip>=23.3",
]
managed = true

[tool.hatch.metadata]
allow-direct-references = true

[tool.black]
extend-exclude = """
_pb2\\.pyi?
| _pb2_grpc\\.pyi?
"""
line-length = 88
target-version = ["py38", "py39", "py310"]

[tool.ruff]
line-length = 88
select = ["E", "F", "W", "B", "I"]
src = ["pyprojects/*/src", "pyprojects/*/src/py"]

[tool.pyright]
exclude = ["**/node_modules", "**/__pycache__"]
include = ["pyprojects/*/src", "pyprojects/*/src/py"]
reportGeneralTypeIssues = "information"
reportOptionalMemberAccess = "information"
reportPrivateImportUsage = "information"
