[package]
build = "build.rs"
edition = "2021"
license = "MIT"
name = "sphinx-jsx"
publish = false
readme = "README.md"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]
name = "sphinx_jsx"

[dependencies]
anyhow = "1.0.79"
html5jsx = {version = "0.0.0", path = "../../crates/html5jsx"}
indexmap = "2.1.0"
katex = "0.4.6"
pyo3 = "0.20.0"
serde_json = "1.0.111"
swc_core = {version = "0.87", features = ["ecma_ast", "ecma_codegen"]}

[build-dependencies]
maturin-utils = {path = "../../crates/maturin-utils"}

[dev-dependencies]
maturin = "1.4.0"
