[package]
build = "build.rs"
edition = "2021"
license = "MIT"
name = "sphinx-jsx"
publish = false
readme = "README.md"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]
name = "sphinx_jsx"
path = "src/rs/lib.rs"

[dependencies]
anyhow = "1.0.79"
pyo3 = "0.20.0"
pyo3-utils = {version = "0.0.0", path = "../../crates/pyo3-utils"}
serde_json = "1.0.111"
swc-utils = {version = "0.0.0", path = "../../crates/swc-utils"}
swc_core = {version = "0.88", features = ["ecma_ast", "ecma_ast_serde", "ecma_codegen"]}

[build-dependencies]
maturin-utils = {path = "../../crates/maturin-utils"}

[dev-dependencies]
maturin = "1.4.0"
