[package]
build = "build.rs"
edition = "2021"
license = "MIT"
name = "sphinx-jsx"
readme = "README.md"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]
name = "sphinx_jsx"

[dependencies]
katex = "0.4.6"
pyo3 = "0.19.0"
swc_core = {version = "0.87.*", features = ["ecma_ast", "ecma_codegen"]}

[build-dependencies]
maturin-utils = {path = "../../crates/maturin-utils"}
