[package]
build = "build.rs"
edition = "2021"
license = "MIT"
name = "sphinx-jsx"
readme = "README.md"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]
name = "sphinx_jsx"

[dependencies]
katex = "0.4.6"
mdxjs = "0.1.19"
minijinja = "1.0.10"
pyo3 = "0.19.0"

[build-dependencies]
maturin-utils = {path = "../../crates/maturin-utils"}
