[package]
edition = "2021"
license.workspace = true
name = "pyo3-utils"
publish = false
version = "0.0.0"

[dependencies]
pyo3 = "0.20.2"

[build-dependencies]
pyo3-build-utils = {path = "../pyo3-build-utils"}
