from typing import Any, Literal, Optional, Type, Union

import orjson
from docutils import nodes
from humps import camelize
from typing_extensions import TypeGuard

from sphinx_jsx.syntax import html, rst
from sphinx_jsx.syntax.jsx.models import (
    JSFragment,
    JSONExpression,
    JSXElement,
    PseudoElement,
    React,
)

from .base import BaseJSXTranslator


class HTML(PseudoElement):
    class head(JSXElement):
        pass

    class style(JSXElement):
        pass

    class span(JSXElement):
        pass

    class div(JSXElement):
        pass

    class p(JSXElement):
        pass

    class em(JSXElement):
        pass

    class strong(JSXElement):
        pass

    class del_(JSXElement, tag_name="del"):
        pass

    class code(JSXElement):
        pass

    class kbd(JSXElement):
        pass

    class sub(JSXElement):
        pass

    class sup(JSXElement):
        pass

    class cite(JSXElement):
        pass

    class abbr(JSXElement):
        title: Optional[str] = None


class Intrinsic(PseudoElement):
    @staticmethod
    def ad_hoc(tag_name: str, *children: JSFragment, **attrs: Any) -> JSXElement:
        name = Intrinsic.sanitize_tag_name(tag_name)

        if name is False:
            return React.Fragment()

        del tag_name

        if well_known := HTML.get_tag_by_name(name):
            return Intrinsic._create_element(well_known, *children, **attrs)

        class _Tag(JSXElement, tag_name=name):
            _intrinsic = True

        return Intrinsic._create_element(_Tag, *children, **attrs)

    @staticmethod
    def sanitize_tag_name(tag_name: str) -> Union[str, Literal[False]]:
        if tag_name in FORBIDDEN_TAGS:
            return False
        return tag_name.lower()

    @staticmethod
    def _create_element(
        t: Type[JSXElement],
        *children: JSFragment,
        **attrs: Any,
    ) -> JSXElement:
        elem = t(children=[*children])

        if id_ := attrs.pop("id", None):
            elem.ids.append(id_)

        if class_ := attrs.pop("class", None):
            elem.classnames.extend(class_.split())

        if style := attrs.pop("style", None):
            elem._style = style

        for key, value in attrs.items():
            key = key.lower()

            if key in FORBIDDEN_PROPS:
                continue

            if key.startswith("data-") or key.startswith("aria-"):
                elem._attrs[key] = value
                continue

            elem._attrs[PROPERTY_INFO.get(key, camelize(key))] = value

        return elem

    @staticmethod
    def is_intrinsic(elem: JSFragment) -> TypeGuard[JSXElement]:
        return isinstance(elem, JSXElement) and bool(getattr(elem, "_intrinsic", False))


class IntrinsicMarkupTranslator(BaseJSXTranslator):
    def visit_Text(self, node: nodes.Text):
        self.append_child(None, JSONExpression(value=node.astext()))

    def visit_paragraph(self, node: nodes.paragraph):
        self.enter_nesting(node, HTML.p())

    def visit_emphasis(self, node: nodes.emphasis):
        self.enter_nesting(node, HTML.em())

    def visit_strong(self, node: nodes.strong):
        self.enter_nesting(node, HTML.strong())

    def visit_literal(self, node: nodes.literal):
        self.enter_nesting(node, HTML.code())

    def visit_kbd(self, node: rst.e.literal__kbd):
        self.enter_nesting(node, HTML.kbd())

    def visit_title_reference(self, node: nodes.title_reference):
        self.enter_nesting(node, HTML.cite())

    def visit_inline(self, node: nodes.inline):
        self.enter_nesting(node, HTML.span())

    def visit_subscript(self, node: nodes.subscript):
        self.enter_nesting(node, HTML.sub())

    def visit_superscript(self, node: nodes.superscript):
        self.enter_nesting(node, HTML.sup())

    def visit_abbreviation(self, node: nodes.abbreviation):
        self.enter_nesting(node, HTML.abbr(title=node.get("explanation")))

    def visit_acronym(self, node: nodes.acronym):
        self.enter_nesting(node, HTML.abbr(title=node.get("explanation")))

    def visit_meta(self, node: nodes.Element):
        meta = Intrinsic.ad_hoc(
            "meta",
            **{
                "name": node.get("name"),
                "content": node.get("content"),
                "lang": node.get("lang"),
                "charset": node.get("charset"),
                "http-equiv": node.get("http-equiv"),
            },
        )
        self.append_child(node, meta)
        raise nodes.SkipNode

    def visit_html_element(self, node: html.e.html_element):
        elem = Intrinsic.ad_hoc(node["name"].lower(), **node.get("attrs", {}))
        self.enter_nesting(node, elem)

    def visit_html_fragment(self, node: html.e.html_fragment):
        self.enter_nesting(node, React.Fragment())


FORBIDDEN_TAGS = {"html", "head", "body", "script"}

# https://react.dev/reference/react-dom/components/common#common
FORBIDDEN_PROPS = {
    k.lower()
    for k in (
        "children",
        "key",
        "ref",
        "dangerouslySetInnerHTML",
        "suppressContentEditableWarning",
        "suppressHydrationWarning",
        "style",
    )
}

# https://github.com/wooorm/property-information
PROPERTY_INFO = orjson.loads(
    """
{
  "xmllang": "xmlLang",
  "xml:lang": "xmlLang",
  "xmlbase": "xmlBase",
  "xml:base": "xmlBase",
  "xmlspace": "xmlSpace",
  "xml:space": "xmlSpace",
  "xlinkactuate": "xLinkActuate",
  "xlink:actuate": "xLinkActuate",
  "xlinkarcrole": "xLinkArcRole",
  "xlink:arcrole": "xLinkArcRole",
  "xlinkhref": "xLinkHref",
  "xlink:href": "xLinkHref",
  "xlinkrole": "xLinkRole",
  "xlink:role": "xLinkRole",
  "xlinkshow": "xLinkShow",
  "xlink:show": "xLinkShow",
  "xlinktitle": "xLinkTitle",
  "xlink:title": "xLinkTitle",
  "xlinktype": "xLinkType",
  "xlink:type": "xLinkType",
  "xmlns": "xmlns",
  "xmlnsxlink": "xmlnsXLink",
  "xmlns:xlink": "xmlnsXLink",
  "ariaactivedescendant": "ariaActiveDescendant",
  "aria-activedescendant": "ariaActiveDescendant",
  "ariaatomic": "ariaAtomic",
  "aria-atomic": "ariaAtomic",
  "ariaautocomplete": "ariaAutoComplete",
  "aria-autocomplete": "ariaAutoComplete",
  "ariabusy": "ariaBusy",
  "aria-busy": "ariaBusy",
  "ariachecked": "ariaChecked",
  "aria-checked": "ariaChecked",
  "ariacolcount": "ariaColCount",
  "aria-colcount": "ariaColCount",
  "ariacolindex": "ariaColIndex",
  "aria-colindex": "ariaColIndex",
  "ariacolspan": "ariaColSpan",
  "aria-colspan": "ariaColSpan",
  "ariacontrols": "ariaControls",
  "aria-controls": "ariaControls",
  "ariacurrent": "ariaCurrent",
  "aria-current": "ariaCurrent",
  "ariadescribedby": "ariaDescribedBy",
  "aria-describedby": "ariaDescribedBy",
  "ariadetails": "ariaDetails",
  "aria-details": "ariaDetails",
  "ariadisabled": "ariaDisabled",
  "aria-disabled": "ariaDisabled",
  "ariadropeffect": "ariaDropEffect",
  "aria-dropeffect": "ariaDropEffect",
  "ariaerrormessage": "ariaErrorMessage",
  "aria-errormessage": "ariaErrorMessage",
  "ariaexpanded": "ariaExpanded",
  "aria-expanded": "ariaExpanded",
  "ariaflowto": "ariaFlowTo",
  "aria-flowto": "ariaFlowTo",
  "ariagrabbed": "ariaGrabbed",
  "aria-grabbed": "ariaGrabbed",
  "ariahaspopup": "ariaHasPopup",
  "aria-haspopup": "ariaHasPopup",
  "ariahidden": "ariaHidden",
  "aria-hidden": "ariaHidden",
  "ariainvalid": "ariaInvalid",
  "aria-invalid": "ariaInvalid",
  "ariakeyshortcuts": "ariaKeyShortcuts",
  "aria-keyshortcuts": "ariaKeyShortcuts",
  "arialabel": "ariaLabel",
  "aria-label": "ariaLabel",
  "arialabelledby": "ariaLabelledBy",
  "aria-labelledby": "ariaLabelledBy",
  "arialevel": "ariaLevel",
  "aria-level": "ariaLevel",
  "arialive": "ariaLive",
  "aria-live": "ariaLive",
  "ariamodal": "ariaModal",
  "aria-modal": "ariaModal",
  "ariamultiline": "ariaMultiLine",
  "aria-multiline": "ariaMultiLine",
  "ariamultiselectable": "ariaMultiSelectable",
  "aria-multiselectable": "ariaMultiSelectable",
  "ariaorientation": "ariaOrientation",
  "aria-orientation": "ariaOrientation",
  "ariaowns": "ariaOwns",
  "aria-owns": "ariaOwns",
  "ariaplaceholder": "ariaPlaceholder",
  "aria-placeholder": "ariaPlaceholder",
  "ariaposinset": "ariaPosInSet",
  "aria-posinset": "ariaPosInSet",
  "ariapressed": "ariaPressed",
  "aria-pressed": "ariaPressed",
  "ariareadonly": "ariaReadOnly",
  "aria-readonly": "ariaReadOnly",
  "ariarelevant": "ariaRelevant",
  "aria-relevant": "ariaRelevant",
  "ariarequired": "ariaRequired",
  "aria-required": "ariaRequired",
  "ariaroledescription": "ariaRoleDescription",
  "aria-roledescription": "ariaRoleDescription",
  "ariarowcount": "ariaRowCount",
  "aria-rowcount": "ariaRowCount",
  "ariarowindex": "ariaRowIndex",
  "aria-rowindex": "ariaRowIndex",
  "ariarowspan": "ariaRowSpan",
  "aria-rowspan": "ariaRowSpan",
  "ariaselected": "ariaSelected",
  "aria-selected": "ariaSelected",
  "ariasetsize": "ariaSetSize",
  "aria-setsize": "ariaSetSize",
  "ariasort": "ariaSort",
  "aria-sort": "ariaSort",
  "ariavaluemax": "ariaValueMax",
  "aria-valuemax": "ariaValueMax",
  "ariavaluemin": "ariaValueMin",
  "aria-valuemin": "ariaValueMin",
  "ariavaluenow": "ariaValueNow",
  "aria-valuenow": "ariaValueNow",
  "ariavaluetext": "ariaValueText",
  "aria-valuetext": "ariaValueText",
  "role": "role",
  "about": "about",
  "accentheight": "accentHeight",
  "accent-height": "accentHeight",
  "accumulate": "accumulate",
  "additive": "additive",
  "alignmentbaseline": "alignmentBaseline",
  "alignment-baseline": "alignmentBaseline",
  "alphabetic": "alphabetic",
  "amplitude": "amplitude",
  "arabicform": "arabicForm",
  "arabic-form": "arabicForm",
  "ascent": "ascent",
  "attributename": "attributeName",
  "attributetype": "attributeType",
  "azimuth": "azimuth",
  "bandwidth": "bandwidth",
  "baselineshift": "baselineShift",
  "baseline-shift": "baselineShift",
  "basefrequency": "baseFrequency",
  "baseprofile": "baseProfile",
  "bbox": "bbox",
  "begin": "begin",
  "bias": "bias",
  "by": "by",
  "calcmode": "calcMode",
  "capheight": "capHeight",
  "cap-height": "capHeight",
  "classname": "className",
  "class": "className",
  "clip": "clip",
  "clippath": "clipPath",
  "clip-path": "clipPath",
  "clippathunits": "clipPathUnits",
  "cliprule": "clipRule",
  "clip-rule": "clipRule",
  "color": "color",
  "colorinterpolation": "colorInterpolation",
  "color-interpolation": "colorInterpolation",
  "colorinterpolationfilters": "colorInterpolationFilters",
  "color-interpolation-filters": "colorInterpolationFilters",
  "colorprofile": "colorProfile",
  "color-profile": "colorProfile",
  "colorrendering": "colorRendering",
  "color-rendering": "colorRendering",
  "content": "content",
  "contentscripttype": "contentScriptType",
  "contentstyletype": "contentStyleType",
  "crossorigin": "crossOrigin",
  "cursor": "cursor",
  "cx": "cx",
  "cy": "cy",
  "d": "d",
  "datatype": "dataType",
  "defaultaction": "defaultAction",
  "descent": "descent",
  "diffuseconstant": "diffuseConstant",
  "direction": "direction",
  "display": "display",
  "dur": "dur",
  "divisor": "divisor",
  "dominantbaseline": "dominantBaseline",
  "dominant-baseline": "dominantBaseline",
  "download": "download",
  "dx": "dx",
  "dy": "dy",
  "edgemode": "edgeMode",
  "editable": "editable",
  "elevation": "elevation",
  "enablebackground": "enableBackground",
  "enable-background": "enableBackground",
  "end": "end",
  "event": "event",
  "exponent": "exponent",
  "externalresourcesrequired": "externalResourcesRequired",
  "fill": "fill",
  "fillopacity": "fillOpacity",
  "fill-opacity": "fillOpacity",
  "fillrule": "fillRule",
  "fill-rule": "fillRule",
  "filter": "filter",
  "filterres": "filterRes",
  "filterunits": "filterUnits",
  "floodcolor": "floodColor",
  "flood-color": "floodColor",
  "floodopacity": "floodOpacity",
  "flood-opacity": "floodOpacity",
  "focusable": "focusable",
  "focushighlight": "focusHighlight",
  "fontfamily": "fontFamily",
  "font-family": "fontFamily",
  "fontsize": "fontSize",
  "font-size": "fontSize",
  "fontsizeadjust": "fontSizeAdjust",
  "font-size-adjust": "fontSizeAdjust",
  "fontstretch": "fontStretch",
  "font-stretch": "fontStretch",
  "fontstyle": "fontStyle",
  "font-style": "fontStyle",
  "fontvariant": "fontVariant",
  "font-variant": "fontVariant",
  "fontweight": "fontWeight",
  "font-weight": "fontWeight",
  "format": "format",
  "fr": "fr",
  "from": "from",
  "fx": "fx",
  "fy": "fy",
  "g1": "g1",
  "g2": "g2",
  "glyphname": "glyphName",
  "glyph-name": "glyphName",
  "glyphorientationhorizontal": "glyphOrientationHorizontal",
  "glyph-orientation-horizontal": "glyphOrientationHorizontal",
  "glyphorientationvertical": "glyphOrientationVertical",
  "glyph-orientation-vertical": "glyphOrientationVertical",
  "glyphref": "glyphRef",
  "gradienttransform": "gradientTransform",
  "gradientunits": "gradientUnits",
  "handler": "handler",
  "hanging": "hanging",
  "hatchcontentunits": "hatchContentUnits",
  "hatchunits": "hatchUnits",
  "height": "height",
  "href": "href",
  "hreflang": "hrefLang",
  "horizadvx": "horizAdvX",
  "horiz-adv-x": "horizAdvX",
  "horizoriginx": "horizOriginX",
  "horiz-origin-x": "horizOriginX",
  "horizoriginy": "horizOriginY",
  "horiz-origin-y": "horizOriginY",
  "id": "id",
  "ideographic": "ideographic",
  "imagerendering": "imageRendering",
  "image-rendering": "imageRendering",
  "initialvisibility": "initialVisibility",
  "in": "in",
  "in2": "in2",
  "intercept": "intercept",
  "k": "k",
  "k1": "k1",
  "k2": "k2",
  "k3": "k3",
  "k4": "k4",
  "kernelmatrix": "kernelMatrix",
  "kernelunitlength": "kernelUnitLength",
  "keypoints": "keyPoints",
  "keysplines": "keySplines",
  "keytimes": "keyTimes",
  "kerning": "kerning",
  "lang": "lang",
  "lengthadjust": "lengthAdjust",
  "letterspacing": "letterSpacing",
  "letter-spacing": "letterSpacing",
  "lightingcolor": "lightingColor",
  "lighting-color": "lightingColor",
  "limitingconeangle": "limitingConeAngle",
  "local": "local",
  "markerend": "markerEnd",
  "marker-end": "markerEnd",
  "markermid": "markerMid",
  "marker-mid": "markerMid",
  "markerstart": "markerStart",
  "marker-start": "markerStart",
  "markerheight": "markerHeight",
  "markerunits": "markerUnits",
  "markerwidth": "markerWidth",
  "mask": "mask",
  "maskcontentunits": "maskContentUnits",
  "maskunits": "maskUnits",
  "mathematical": "mathematical",
  "max": "max",
  "media": "media",
  "mediacharacterencoding": "mediaCharacterEncoding",
  "mediacontentencodings": "mediaContentEncodings",
  "mediasize": "mediaSize",
  "mediatime": "mediaTime",
  "method": "method",
  "min": "min",
  "mode": "mode",
  "name": "name",
  "navdown": "navDown",
  "nav-down": "navDown",
  "navdownleft": "navDownLeft",
  "nav-down-left": "navDownLeft",
  "navdownright": "navDownRight",
  "nav-down-right": "navDownRight",
  "navleft": "navLeft",
  "nav-left": "navLeft",
  "navnext": "navNext",
  "nav-next": "navNext",
  "navprev": "navPrev",
  "nav-prev": "navPrev",
  "navright": "navRight",
  "nav-right": "navRight",
  "navup": "navUp",
  "nav-up": "navUp",
  "navupleft": "navUpLeft",
  "nav-up-left": "navUpLeft",
  "navupright": "navUpRight",
  "nav-up-right": "navUpRight",
  "numoctaves": "numOctaves",
  "observer": "observer",
  "offset": "offset",
  "onabort": "onAbort",
  "onactivate": "onActivate",
  "onafterprint": "onAfterPrint",
  "onbeforeprint": "onBeforePrint",
  "onbegin": "onBegin",
  "oncancel": "onCancel",
  "oncanplay": "onCanPlay",
  "oncanplaythrough": "onCanPlayThrough",
  "onchange": "onChange",
  "onclick": "onClick",
  "onclose": "onClose",
  "oncopy": "onCopy",
  "oncuechange": "onCueChange",
  "oncut": "onCut",
  "ondblclick": "onDblClick",
  "ondrag": "onDrag",
  "ondragend": "onDragEnd",
  "ondragenter": "onDragEnter",
  "ondragexit": "onDragExit",
  "ondragleave": "onDragLeave",
  "ondragover": "onDragOver",
  "ondragstart": "onDragStart",
  "ondrop": "onDrop",
  "ondurationchange": "onDurationChange",
  "onemptied": "onEmptied",
  "onend": "onEnd",
  "onended": "onEnded",
  "onerror": "onError",
  "onfocus": "onFocus",
  "onfocusin": "onFocusIn",
  "onfocusout": "onFocusOut",
  "onhashchange": "onHashChange",
  "oninput": "onInput",
  "oninvalid": "onInvalid",
  "onkeydown": "onKeyDown",
  "onkeypress": "onKeyPress",
  "onkeyup": "onKeyUp",
  "onload": "onLoad",
  "onloadeddata": "onLoadedData",
  "onloadedmetadata": "onLoadedMetadata",
  "onloadstart": "onLoadStart",
  "onmessage": "onMessage",
  "onmousedown": "onMouseDown",
  "onmouseenter": "onMouseEnter",
  "onmouseleave": "onMouseLeave",
  "onmousemove": "onMouseMove",
  "onmouseout": "onMouseOut",
  "onmouseover": "onMouseOver",
  "onmouseup": "onMouseUp",
  "onmousewheel": "onMouseWheel",
  "onoffline": "onOffline",
  "ononline": "onOnline",
  "onpagehide": "onPageHide",
  "onpageshow": "onPageShow",
  "onpaste": "onPaste",
  "onpause": "onPause",
  "onplay": "onPlay",
  "onplaying": "onPlaying",
  "onpopstate": "onPopState",
  "onprogress": "onProgress",
  "onratechange": "onRateChange",
  "onrepeat": "onRepeat",
  "onreset": "onReset",
  "onresize": "onResize",
  "onscroll": "onScroll",
  "onseeked": "onSeeked",
  "onseeking": "onSeeking",
  "onselect": "onSelect",
  "onshow": "onShow",
  "onstalled": "onStalled",
  "onstorage": "onStorage",
  "onsubmit": "onSubmit",
  "onsuspend": "onSuspend",
  "ontimeupdate": "onTimeUpdate",
  "ontoggle": "onToggle",
  "onunload": "onUnload",
  "onvolumechange": "onVolumeChange",
  "onwaiting": "onWaiting",
  "onzoom": "onZoom",
  "opacity": "opacity",
  "operator": "operator",
  "order": "order",
  "orient": "orient",
  "orientation": "orientation",
  "origin": "origin",
  "overflow": "overflow",
  "overlay": "overlay",
  "overlineposition": "overlinePosition",
  "overline-position": "overlinePosition",
  "overlinethickness": "overlineThickness",
  "overline-thickness": "overlineThickness",
  "paintorder": "paintOrder",
  "paint-order": "paintOrder",
  "panose1": "panose1",
  "panose-1": "panose1",
  "path": "path",
  "pathlength": "pathLength",
  "patterncontentunits": "patternContentUnits",
  "patterntransform": "patternTransform",
  "patternunits": "patternUnits",
  "phase": "phase",
  "ping": "ping",
  "pitch": "pitch",
  "playbackorder": "playbackOrder",
  "pointerevents": "pointerEvents",
  "pointer-events": "pointerEvents",
  "points": "points",
  "pointsatx": "pointsAtX",
  "pointsaty": "pointsAtY",
  "pointsatz": "pointsAtZ",
  "preservealpha": "preserveAlpha",
  "preserveaspectratio": "preserveAspectRatio",
  "primitiveunits": "primitiveUnits",
  "propagate": "propagate",
  "property": "property",
  "r": "r",
  "radius": "radius",
  "referrerpolicy": "referrerPolicy",
  "refx": "refX",
  "refy": "refY",
  "rel": "rel",
  "rev": "rev",
  "renderingintent": "renderingIntent",
  "rendering-intent": "renderingIntent",
  "repeatcount": "repeatCount",
  "repeatdur": "repeatDur",
  "requiredextensions": "requiredExtensions",
  "requiredfeatures": "requiredFeatures",
  "requiredfonts": "requiredFonts",
  "requiredformats": "requiredFormats",
  "resource": "resource",
  "restart": "restart",
  "result": "result",
  "rotate": "rotate",
  "rx": "rx",
  "ry": "ry",
  "scale": "scale",
  "seed": "seed",
  "shaperendering": "shapeRendering",
  "shape-rendering": "shapeRendering",
  "side": "side",
  "slope": "slope",
  "snapshottime": "snapshotTime",
  "specularconstant": "specularConstant",
  "specularexponent": "specularExponent",
  "spreadmethod": "spreadMethod",
  "spacing": "spacing",
  "startoffset": "startOffset",
  "stddeviation": "stdDeviation",
  "stemh": "stemh",
  "stemv": "stemv",
  "stitchtiles": "stitchTiles",
  "stopcolor": "stopColor",
  "stop-color": "stopColor",
  "stopopacity": "stopOpacity",
  "stop-opacity": "stopOpacity",
  "strikethroughposition": "strikethroughPosition",
  "strikethrough-position": "strikethroughPosition",
  "strikethroughthickness": "strikethroughThickness",
  "strikethrough-thickness": "strikethroughThickness",
  "string": "string",
  "stroke": "stroke",
  "strokedasharray": "strokeDashArray",
  "stroke-dasharray": "strokeDashArray",
  "strokedashoffset": "strokeDashOffset",
  "stroke-dashoffset": "strokeDashOffset",
  "strokelinecap": "strokeLineCap",
  "stroke-linecap": "strokeLineCap",
  "strokelinejoin": "strokeLineJoin",
  "stroke-linejoin": "strokeLineJoin",
  "strokemiterlimit": "strokeMiterLimit",
  "stroke-miterlimit": "strokeMiterLimit",
  "strokeopacity": "strokeOpacity",
  "stroke-opacity": "strokeOpacity",
  "strokewidth": "strokeWidth",
  "stroke-width": "strokeWidth",
  "style": "style",
  "surfacescale": "surfaceScale",
  "syncbehavior": "syncBehavior",
  "syncbehaviordefault": "syncBehaviorDefault",
  "syncmaster": "syncMaster",
  "synctolerance": "syncTolerance",
  "synctolerancedefault": "syncToleranceDefault",
  "systemlanguage": "systemLanguage",
  "tabindex": "tabIndex",
  "tablevalues": "tableValues",
  "target": "target",
  "targetx": "targetX",
  "targety": "targetY",
  "textanchor": "textAnchor",
  "text-anchor": "textAnchor",
  "textdecoration": "textDecoration",
  "text-decoration": "textDecoration",
  "textrendering": "textRendering",
  "text-rendering": "textRendering",
  "textlength": "textLength",
  "timelinebegin": "timelineBegin",
  "title": "title",
  "transformbehavior": "transformBehavior",
  "type": "type",
  "typeof": "typeOf",
  "to": "to",
  "transform": "transform",
  "transformorigin": "transformOrigin",
  "transform-origin": "transformOrigin",
  "u1": "u1",
  "u2": "u2",
  "underlineposition": "underlinePosition",
  "underline-position": "underlinePosition",
  "underlinethickness": "underlineThickness",
  "underline-thickness": "underlineThickness",
  "unicode": "unicode",
  "unicodebidi": "unicodeBidi",
  "unicode-bidi": "unicodeBidi",
  "unicoderange": "unicodeRange",
  "unicode-range": "unicodeRange",
  "unitsperem": "unitsPerEm",
  "units-per-em": "unitsPerEm",
  "values": "values",
  "valphabetic": "vAlphabetic",
  "v-alphabetic": "vAlphabetic",
  "vmathematical": "vMathematical",
  "v-mathematical": "vMathematical",
  "vectoreffect": "vectorEffect",
  "vector-effect": "vectorEffect",
  "vhanging": "vHanging",
  "v-hanging": "vHanging",
  "videographic": "vIdeographic",
  "v-ideographic": "vIdeographic",
  "version": "version",
  "vertadvy": "vertAdvY",
  "vert-adv-y": "vertAdvY",
  "vertoriginx": "vertOriginX",
  "vert-origin-x": "vertOriginX",
  "vertoriginy": "vertOriginY",
  "vert-origin-y": "vertOriginY",
  "viewbox": "viewBox",
  "viewtarget": "viewTarget",
  "visibility": "visibility",
  "width": "width",
  "widths": "widths",
  "wordspacing": "wordSpacing",
  "word-spacing": "wordSpacing",
  "writingmode": "writingMode",
  "writing-mode": "writingMode",
  "x": "x",
  "x1": "x1",
  "x2": "x2",
  "xchannelselector": "xChannelSelector",
  "xheight": "xHeight",
  "x-height": "xHeight",
  "y": "y",
  "y1": "y1",
  "y2": "y2",
  "ychannelselector": "yChannelSelector",
  "z": "z",
  "zoomandpan": "zoomAndPan",
  "abbr": "abbr",
  "accept": "accept",
  "acceptcharset": "acceptCharset",
  "accept-charset": "acceptCharset",
  "accesskey": "accessKey",
  "action": "action",
  "allow": "allow",
  "allowfullscreen": "allowFullScreen",
  "allowpaymentrequest": "allowPaymentRequest",
  "allowusermedia": "allowUserMedia",
  "alt": "alt",
  "as": "as",
  "async": "async",
  "autocapitalize": "autoCapitalize",
  "autocomplete": "autoComplete",
  "autofocus": "autoFocus",
  "autoplay": "autoPlay",
  "blocking": "blocking",
  "capture": "capture",
  "charset": "charSet",
  "checked": "checked",
  "cite": "cite",
  "cols": "cols",
  "colspan": "colSpan",
  "contenteditable": "contentEditable",
  "controls": "controls",
  "controlslist": "controlsList",
  "coords": "coords",
  "data": "data",
  "datetime": "dateTime",
  "decoding": "decoding",
  "default": "default",
  "defer": "defer",
  "dir": "dir",
  "dirname": "dirName",
  "disabled": "disabled",
  "draggable": "draggable",
  "enctype": "encType",
  "enterkeyhint": "enterKeyHint",
  "fetchpriority": "fetchPriority",
  "form": "form",
  "formaction": "formAction",
  "formenctype": "formEncType",
  "formmethod": "formMethod",
  "formnovalidate": "formNoValidate",
  "formtarget": "formTarget",
  "headers": "headers",
  "hidden": "hidden",
  "high": "high",
  "htmlfor": "htmlFor",
  "for": "htmlFor",
  "httpequiv": "httpEquiv",
  "http-equiv": "httpEquiv",
  "imagesizes": "imageSizes",
  "imagesrcset": "imageSrcSet",
  "inert": "inert",
  "inputmode": "inputMode",
  "integrity": "integrity",
  "is": "is",
  "ismap": "isMap",
  "itemid": "itemId",
  "itemprop": "itemProp",
  "itemref": "itemRef",
  "itemscope": "itemScope",
  "itemtype": "itemType",
  "kind": "kind",
  "label": "label",
  "language": "language",
  "list": "list",
  "loading": "loading",
  "loop": "loop",
  "low": "low",
  "manifest": "manifest",
  "maxlength": "maxLength",
  "minlength": "minLength",
  "multiple": "multiple",
  "muted": "muted",
  "nonce": "nonce",
  "nomodule": "noModule",
  "novalidate": "noValidate",
  "onauxclick": "onAuxClick",
  "onbeforematch": "onBeforeMatch",
  "onbeforetoggle": "onBeforeToggle",
  "onbeforeunload": "onBeforeUnload",
  "onblur": "onBlur",
  "oncontextlost": "onContextLost",
  "oncontextmenu": "onContextMenu",
  "oncontextrestored": "onContextRestored",
  "onformdata": "onFormData",
  "onlanguagechange": "onLanguageChange",
  "onloadend": "onLoadEnd",
  "onmessageerror": "onMessageError",
  "onrejectionhandled": "onRejectionHandled",
  "onscrollend": "onScrollEnd",
  "onsecuritypolicyviolation": "onSecurityPolicyViolation",
  "onslotchange": "onSlotChange",
  "onunhandledrejection": "onUnhandledRejection",
  "onwheel": "onWheel",
  "open": "open",
  "optimum": "optimum",
  "pattern": "pattern",
  "placeholder": "placeholder",
  "playsinline": "playsInline",
  "popover": "popover",
  "popovertarget": "popoverTarget",
  "popovertargetaction": "popoverTargetAction",
  "poster": "poster",
  "preload": "preload",
  "readonly": "readOnly",
  "required": "required",
  "reversed": "reversed",
  "rows": "rows",
  "rowspan": "rowSpan",
  "sandbox": "sandbox",
  "scope": "scope",
  "scoped": "scoped",
  "seamless": "seamless",
  "selected": "selected",
  "shadowrootdelegatesfocus": "shadowRootDelegatesFocus",
  "shadowrootmode": "shadowRootMode",
  "shape": "shape",
  "size": "size",
  "sizes": "sizes",
  "slot": "slot",
  "span": "span",
  "spellcheck": "spellCheck",
  "src": "src",
  "srcdoc": "srcDoc",
  "srclang": "srcLang",
  "srcset": "srcSet",
  "start": "start",
  "step": "step",
  "translate": "translate",
  "typemustmatch": "typeMustMatch",
  "usemap": "useMap",
  "value": "value",
  "wrap": "wrap",
  "align": "align",
  "alink": "aLink",
  "archive": "archive",
  "axis": "axis",
  "background": "background",
  "bgcolor": "bgColor",
  "border": "border",
  "bordercolor": "borderColor",
  "bottommargin": "bottomMargin",
  "cellpadding": "cellPadding",
  "cellspacing": "cellSpacing",
  "char": "char",
  "charoff": "charOff",
  "classid": "classId",
  "clear": "clear",
  "code": "code",
  "codebase": "codeBase",
  "codetype": "codeType",
  "compact": "compact",
  "declare": "declare",
  "face": "face",
  "frame": "frame",
  "frameborder": "frameBorder",
  "hspace": "hSpace",
  "leftmargin": "leftMargin",
  "link": "link",
  "longdesc": "longDesc",
  "lowsrc": "lowSrc",
  "marginheight": "marginHeight",
  "marginwidth": "marginWidth",
  "noresize": "noResize",
  "nohref": "noHref",
  "noshade": "noShade",
  "nowrap": "noWrap",
  "object": "object",
  "profile": "profile",
  "prompt": "prompt",
  "rightmargin": "rightMargin",
  "rules": "rules",
  "scheme": "scheme",
  "scrolling": "scrolling",
  "standby": "standby",
  "summary": "summary",
  "text": "text",
  "topmargin": "topMargin",
  "valuetype": "valueType",
  "valign": "vAlign",
  "vlink": "vLink",
  "vspace": "vSpace",
  "allowtransparency": "allowTransparency",
  "autocorrect": "autoCorrect",
  "autosave": "autoSave",
  "disablepictureinpicture": "disablePictureInPicture",
  "disableremoteplayback": "disableRemotePlayback",
  "prefix": "prefix",
  "results": "results",
  "security": "security",
  "unselectable": "unselectable"
}
"""
)
