[package]
edition = "2021"
name = "playground"
publish = false
version = "0.0.0"

[dependencies]
swc-utils = {version = "0.0.0", path = "../swc-utils"}
swc_core = {version = "0.88.1", features = ["ecma_ast", "ecma_ast_serde", "ecma_utils"]}
