[package]
edition = "2021"
license.workspace = true
name = "playground"
publish = false
version = "0.0.0"

[dependencies]
anyhow = "1.0.79"
miette = {version = "5.10.0", features = ["fancy"]}
thiserror = "1.0.56"
