[package]
edition = "2021"
name = "playground"
publish = false
version = "0.0.0"

[dependencies]
pyo3 = "0.20.2"
serde = {version = "1.0.195", features = ["derive"]}
serde_json = "1.0.111"
swc_core = { version = "0.88.1", features = ["ecma_ast", "ecma_ast_serde"] }
