[package]
edition = "2021"
license.workspace = true
name = "sphinx-jsx-macros"
version = "0.0.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.78"
quote = "1.0.35"
syn = {version = "2.0.48", features = ["full"]}
