from typing import Optional, Protocol

class SphinxOptions(Protocol):
    srcdir: str
    outdir: str

class Bundler:
    def __new__(cls, options: SphinxOptions): ...
    def init(self) -> None: ...
    def open(self, path: str) -> Doctree: ...
    def seal(self, doctree: Doctree) -> None: ...
    def emit(self) -> None: ...

class Doctree:
    def element(
        self,
        tag: str,
        attrs: str,
        *,
        file: Optional[str] = None,
        line: Optional[int] = None,
        source: Optional[str] = None,
    ): ...
    def enter(self): ...
    def text(self, text: str): ...
    def exit(self): ...
