[package]
edition = "2021"
license.workspace = true
name = "html5jsx-bin"
publish = false
version = "0.0.0"

[dependencies]
base64 = "0.21.7"
html5jsx = {path = ".."}
swc-ecma-utils2 = {path = "../../swc-ecma-utils2"}
swc_core = {version = "*", features = ["ecma_codegen", "common_sourcemap"]}
