[package]
edition = "2021"
license.workspace = true
name = "swc-plugin-esm-serve"
publish = false
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
esm-serve = {path = "../../crates/esm-serve"}
serde_json = "1.0.111"
swc_core = {version = "*", features = ["ecma_parser"]}
