[package]
edition = "2021"
name = "swc-plugin-esm-serve"
publish = false
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
esm-serve = {version = "0.0.0", path = "../../crates/esm-serve"}
serde_json = "1.0.111"
swc_core = {version = "0.88", features = ["ecma_parser"]}
