[package]
edition = "2021"
license.workspace = true
name = "serde-jsx"
publish = false
version = "0.0.0"

[dependencies]
serde = {version = "1.0.193", features = ["derive"]}
serde_json = {version = "1.0.111", features = ["raw_value"]}
