[package]
edition = "2021"
license.workspace = true
name = "_deno-lite-macros"
version = "0.0.0"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6.0"
proc-macro2 = "1.0.78"
quote = "1.0.35"
syn = {version = "2.0.48", features = ["full"]}
