pub const JSX_ONLY: mdxjs::MdxConstructs = mdxjs::MdxConstructs {
    attention: false,
    block_quote: false,
    character_escape: false,
    character_reference: false,
    code_fenced: false,
    code_text: false,
    definition: false,
    frontmatter: false,
    gfm_autolink_literal: false,
    gfm_footnote_definition: false,
    gfm_label_start_footnote: false,
    gfm_strikethrough: false,
    gfm_table: false,
    gfm_task_list_item: false,
    hard_break_escape: false,
    hard_break_trailing: false,
    heading_atx: false,
    heading_setext: false,
    label_start_image: false,
    label_start_link: false,
    label_end: false,
    list_item: false,
    math_flow: false,
    math_text: false,
    thematic_break: false,
};
