# https://github.com/sveltejs/kit/blob/32afba695088b946aefe96da75b36de9b0667fbe/.github/workflows/release.yml
name: 'Release'

on:
  push:
    branches: ['main']

permissions: {}

jobs:
  changesets:
    # prevents this action from running on forks
    if: github.repository == 'secretflow/doctools'

    name: Changesets
    uses: secretflow/web-ci/.github/workflows/release-changesets.yml@main

    secrets:
      BOT_APP_ID: ${{ secrets.APP_ID }}
      BOT_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)

  ci:
    needs: [changesets]
    if: |
      needs.changesets.outputs.should-release == 'true'

    name: Prerelease CI
    uses: ./.github/workflows/ci.yml

    permissions:
      contents: read
      actions: read

  publish:
    needs: [ci]
    if: |
      needs.ci.result == 'success'

    name: Publish
    uses: secretflow/web-ci/.github/workflows/release-publish.yml@main

    with:
      node-version: 16.20.x
      python-version: 3.8.x

    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      BOT_APP_ID: ${{ secrets.APP_ID }}
      BOT_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

    permissions:
      contents: write # to create tags
