# https://github.com/sveltejs/kit/blob/32afba695088b946aefe96da75b36de9b0667fbe/.github/workflows/release.yml
name: 'Code: Release'

on:
  push:
    branches: ['main']

permissions: {}

jobs:
  release:
    # prevent this action from running on forks
    if: |
      github.repository == 'secretflow/doctools'

    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)

    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # fetch the full history for changesets to generate changelog
          fetch-depth: 0

      - uses: ./.github/actions/ci-setup

      # Generate GitHub token for changesets/action
      # Using https://github.com/secretflow/bot
      # This allows changesets/action to create a release PR using the bot's identity
      # Token goes into env. See action for details
      - name: Generate GitHub token
        uses: wow-actions/use-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Determine if changesets exist
        # If there are changesets, this step will create a release PR
        # If there isn't any changeset, this step will do nothing
        # Instead, later steps will run CI and publish
        id: changesets
        uses: changesets/action@v1
        with:
          # run changeset version to consume all changesets and bump versions
          version: pnpm run version
          # publish with Nx. won't call changeset publish but does call changeset tag
          publish: echo 'No changesets. Will publish packages'
          # title of the release PR
          title: 'chore: release'
          # commit message for the release commits
          commit: 'chore: stage changes for next release'
        env:
          # For changesets/action to create a release PR
          # Comes from wow-actions/use-app-token
          GITHUB_TOKEN: ${{ env.BOT_TOKEN }}

      # hasChangesets == 'false' means will publish
      - if: steps.changesets.outputs.hasChangesets == 'false'
        name: CI
        uses: ./.github/workflows/ci.yml

      - if: steps.changesets.outputs.hasChangesets == 'false'
        name: Authenticate with NPM
        run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"

      - if: steps.changesets.outputs.hasChangesets == 'false'
        name: Publish
        run: pnpm run release && pnpm exec changeset tag && git push --tags
        env:
          HATCH_INDEX_USER: __token__ # For PyPI
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_TOKEN }}
